package main

// Equivalence tests against goldens generated by the Python implementation
// (testdata/generate.py). If either side drifts, its own tests fail against
// the committed files.

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

type goldens struct {
	FtypSize   uint64 `json:"ftyp_size"`
	MoovSize   uint64 `json:"moov_size"`
	CdnSize    uint64 `json:"cdn_size"`
	MoovOffset uint64 `json:"moov_offset"`
	FileSize   uint64 `json:"file_size"`
	Ranges     []struct {
		Start   uint64 `json:"start"`
		End     uint64 `json:"end"`
		BodyB64 string `json:"body_b64"`
	} `json:"ranges"`
	RangeHeaders []struct {
		Header string `json:"header"`
		OK     bool   `json:"ok"`
		Start  uint64 `json:"start"`
		End    uint64 `json:"end"`
	} `json:"range_headers"`
}

func loadGoldens(t *testing.T) (*goldens, *fshInfo, []byte) {
	t.Helper()
	raw, err := os.ReadFile("testdata/expected.json")
	if err != nil {
		t.Fatalf("read goldens: %v", err)
	}
	var g goldens
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse goldens: %v", err)
	}
	info, err := loadFsh("testdata/sample.fsh")
	if err != nil {
		t.Fatalf("load fsh: %v", err)
	}
	cdn, err := os.ReadFile("testdata/cdn.bin")
	if err != nil {
		t.Fatalf("read cdn blob: %v", err)
	}
	return &g, info, cdn
}

func TestFshHeaderFieldsMatchPython(t *testing.T) {
	g, info, _ := loadGoldens(t)
	if info.FtypSize != g.FtypSize || info.MoovSize != g.MoovSize ||
		info.CdnSize != g.CdnSize || info.MoovOffset != g.MoovOffset {
		t.Fatalf("fsh fields %+v do not match goldens %+v", info, g)
	}
	if info.alreadyFast() {
		t.Fatal("golden fsh must not be an already-fast sentinel")
	}
}

// serveVirtual materializes a virtual range the way serveWarm does, with the
// CDN replaced by the golden blob.
func serveVirtual(info *fshInfo, cdn []byte, start, end uint64) []byte {
	var out bytes.Buffer
	for _, reg := range info.virtualRegions(start, end) {
		if reg.FromHeader {
			out.Write(info.Header[reg.HdrStart : reg.HdrEnd+1])
		} else {
			out.Write(cdn[reg.CdnStart : reg.CdnEnd+1])
		}
	}
	return out.Bytes()
}

func TestVirtualRangesMatchPythonServeBytes(t *testing.T) {
	g, info, cdn := loadGoldens(t)
	if len(g.Ranges) == 0 {
		t.Fatal("no golden ranges")
	}
	for _, r := range g.Ranges {
		want, err := base64.StdEncoding.DecodeString(r.BodyB64)
		if err != nil {
			t.Fatalf("bad golden body: %v", err)
		}
		got := serveVirtual(info, cdn, r.Start, r.End)
		if !bytes.Equal(got, want) {
			t.Errorf("range %d-%d: %d bytes, want %d; first diff at %d",
				r.Start, r.End, len(got), len(want), firstDiff(got, want))
		}
	}
}

func TestRangeHeaderParsingMatchesPython(t *testing.T) {
	g, _, _ := loadGoldens(t)
	if len(g.RangeHeaders) == 0 {
		t.Fatal("no golden range headers")
	}
	for _, c := range g.RangeHeaders {
		start, end, err := parseByteRange(c.Header, g.FileSize)
		if c.OK != (err == nil) {
			t.Errorf("%q: ok=%v, want %v (err=%v)", c.Header, err == nil, c.OK, err)
			continue
		}
		if !c.OK {
			continue
		}
		if end > g.FileSize-1 {
			end = g.FileSize - 1
		}
		if start != c.Start || end != c.End {
			t.Errorf("%q: got %d-%d, want %d-%d", c.Header, start, end, c.Start, c.End)
		}
	}
}

func firstDiff(a, b []byte) int {
	n := min(len(a), len(b))
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return n
}
