"""Pins Python's streaming byte math to the goldens the Go front tests
against (spore-stream/testdata/, generated by generate.py there). If either
implementation drifts from the committed files, its own tests fail.

Also covers the seam between the two: the /internal/stream-resolve endpoint
that hands the Go front its serving decision.
"""
import base64
import json
import os
import re
import struct
import sys

os.environ.setdefault("TORBOX_API_KEY", "test")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest

import mp4_faststart

_ROOT = os.path.join(os.path.dirname(__file__), "..")
_TESTDATA = os.path.join(_ROOT, "spore-stream", "testdata")


def _src(relpath):
    with open(os.path.join(_ROOT, relpath), encoding="utf-8") as f:
        return f.read()


@pytest.fixture()
def goldens():
    with open(os.path.join(_TESTDATA, "expected.json")) as f:
        exp = json.load(f)
    with open(os.path.join(_TESTDATA, "cdn.bin"), "rb") as f:
        cdn = f.read()
    return exp, cdn


def test_fsh_load_matches_the_goldens(goldens):
    exp, _ = goldens
    mp4_faststart.init(_TESTDATA)
    info = mp4_faststart.load("sample")
    assert info is not None
    assert info["ftyp_size"] == exp["ftyp_size"]
    assert info["moov_size"] == exp["moov_size"]
    assert info["cdn_size"] == exp["cdn_size"]
    assert info["moov_offset"] == exp["moov_offset"]
    assert not info["already_fast"]


def test_serve_bytes_matches_the_goldens(goldens, monkeypatch):
    exp, cdn = goldens
    mp4_faststart.init(_TESTDATA)
    info = mp4_faststart.load("sample")
    monkeypatch.setattr(mp4_faststart, "_get",
                        lambda url, start, end, **kw: cdn[start:end + 1])
    assert exp["ranges"], "no golden ranges"
    for r in exp["ranges"]:
        got = mp4_faststart.serve_bytes(info, "http://fake", r["start"], r["end"])
        want = base64.b64decode(r["body_b64"])
        assert got == want, f"range {r['start']}-{r['end']} diverged from goldens"


def test_golden_fsh_is_the_documented_format():
    """The Go side parses this layout independently; the prefix must stay
    [8B ftyp][8B moov][8B cdn][8B moov_offset]."""
    with open(os.path.join(_TESTDATA, "sample.fsh"), "rb") as f:
        raw = f.read()
    ftyp, moov, cdn, moov_off = struct.unpack_from(">QQQQ", raw, 0)
    assert (ftyp, moov, cdn, moov_off) == (16, 100, 1000, 600)
    assert len(raw) == 32 + ftyp + moov


# -- the resolve seam ---------------------------------------------------------

def test_internal_resolve_is_loopback_only():
    src = _src("app.py")
    m = re.search(
        r'@app\.get\(["\']/internal/stream-resolve/<token>["\']\)\s*\n'
        r"def internal_stream_resolve\(.*?\n(.*?)\n@app\.", src, re.S)
    assert m, "internal resolve endpoint not found"
    body = m.group(1)
    assert '"127.0.0.1"' in body and "403" in body


def test_internal_paths_skip_session_auth_but_nothing_else_changed():
    """The Go front calls resolve over loopback with no session. The auth
    gate lets /internal/ through; the endpoint's own loopback check is the
    guard."""
    src = _src("auth.py")
    assert '"/internal/"' in src


def test_flask_route_and_resolve_share_one_decision_function():
    """The Flask route stays a complete fallback (STREAM_FRONT_ENABLED=false)
    and must not fork from what the Go front is told."""
    src = _src("app.py")
    route = re.search(r"def spore_stream_proxy\(.*?\n(.*?)\n@app\.", src, re.S)
    internal = re.search(r"def internal_stream_resolve\(.*?\n(.*?)\n@app\.", src, re.S)
    assert route and "_resolve_stream_mode(" in route.group(1)
    assert internal and "_resolve_stream_mode(" in internal.group(1)


def test_dockerfile_wires_the_go_front():
    src = _src("Dockerfile")
    assert "spore-stream" in src
    assert "STREAM_FRONT_ENABLED" in src
    # Rollback path: front disabled binds gunicorn to the exposed port.
    assert re.search(r"STREAM_FRONT_ENABLED[^\n]*false", src) or "else" in src
