"""Golden fixtures for the Go streaming front, generated by the Python
implementation it must match.

Run from the repo root:  .venv-sdd/bin/python spore-stream/testdata/generate.py

Produces, in this directory:
  cdn.bin        the synthetic CDN file (mdat-after-moov layout)
  sample.fsh     the .fsh cache mp4_faststart would serve from
  expected.json  serve_bytes() output for a matrix of virtual ranges, plus
                 _parse_byte_range() verdicts for a matrix of Range headers

tests/test_stream_goldens.py pins Python to these same files, so if either
implementation drifts from the committed goldens, a test fails on its side.
"""
import base64
import json
import os
import random
import struct
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
os.environ.setdefault("TORBOX_API_KEY", "test")

HERE = os.path.dirname(os.path.abspath(__file__))

FTYP_SIZE, MOOV_SIZE, CDN_SIZE, MOOV_OFFSET = 16, 100, 1000, 600

RANGES = [
    (0, 999),    # full file
    (0, 15),     # ftyp only
    (0, 115),    # exactly the cached header
    (10, 200),   # header into mdat1
    (115, 117),  # header/mdat1 boundary
    (116, 116),  # first mdat1 byte
    (200, 699),  # mdat1 only, up to the mdat2 boundary
    (650, 750),  # spans mdat1 -> mdat2
    (700, 999),  # mdat2 only
    (999, 999),  # last byte
]

RANGE_HEADERS = [
    "bytes=0-499", "bytes=500-", "bytes=-500", "bytes=-2000",
    "bytes=999-", "bytes=1000-", "bytes=5-2", "bytes=", "bytes=abc-def",
]


def main():
    rnd = random.Random(20260831)
    cdn = bytes(rnd.randrange(256) for _ in range(CDN_SIZE))
    header = cdn[:FTYP_SIZE] + bytes((7 * i + 13) % 256 for i in range(MOOV_SIZE))
    fsh = struct.pack(">QQQQ", FTYP_SIZE, MOOV_SIZE, CDN_SIZE, MOOV_OFFSET) + header

    with open(os.path.join(HERE, "cdn.bin"), "wb") as f:
        f.write(cdn)
    with open(os.path.join(HERE, "sample.fsh"), "wb") as f:
        f.write(fsh)

    import mp4_faststart

    mp4_faststart.init(HERE)
    info = mp4_faststart.load("sample")
    assert info and not info["already_fast"]

    orig_get = mp4_faststart._get
    mp4_faststart._get = lambda url, start, end, **kw: cdn[start:end + 1]
    try:
        ranges_out = []
        for v_start, v_end in RANGES:
            data = mp4_faststart.serve_bytes(info, "http://fake", v_start, v_end)
            ranges_out.append({
                "start": v_start, "end": v_end,
                "body_b64": base64.b64encode(data).decode(),
            })
    finally:
        mp4_faststart._get = orig_get

    # Mirrors app._parse_byte_range (importing app pulls in the whole server).
    def parse_byte_range(range_hdr, file_size):
        _, ranges_str = range_hdr.split("=", 1)
        r_start_s, r_end_s = ranges_str.split("-", 1)
        if not r_start_s:
            if not r_end_s:
                raise ValueError("empty")
            suffix_len = int(r_end_s)
            r_start = max(0, file_size - suffix_len)
            r_end = file_size - 1
        else:
            r_start = int(r_start_s)
            r_end = int(r_end_s) if r_end_s else file_size - 1
        if r_start < 0 or r_start >= file_size or r_start > r_end:
            raise ValueError("unsatisfiable")
        return r_start, r_end

    headers_out = []
    for hdr in RANGE_HEADERS:
        try:
            s, e = parse_byte_range(hdr, CDN_SIZE)
            headers_out.append({"header": hdr, "ok": True, "start": s, "end": min(e, CDN_SIZE - 1)})
        except Exception:
            headers_out.append({"header": hdr, "ok": False})

    with open(os.path.join(HERE, "expected.json"), "w") as f:
        json.dump({
            "ftyp_size": FTYP_SIZE, "moov_size": MOOV_SIZE,
            "cdn_size": CDN_SIZE, "moov_offset": MOOV_OFFSET,
            "file_size": CDN_SIZE,
            "ranges": ranges_out, "range_headers": headers_out,
        }, f, indent=1)
    print("goldens written")


if __name__ == "__main__":
    main()
